version: '3'
services:
  ucf-fe:
    image: ucf-fe
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.ucf-fe-http.rule=Host(`ucffe.example.com`)
        - traefik.http.routers.ucf-fe-http.entrypoints=http
        - traefik.http.routers.ucf-fe-http.middlewares=https-redirect
        - traefik.http.routers.ucf-fe-https.rule=Host(`ucffe.example.com`)
        - traefik.http.routers.ucf-fe-https.entrypoints=https
        - traefik.http.routers.ucf-fe-https.tls=true
        - traefik.http.routers.ucf-fe-https.tls.certresolver=le
        - traefik.http.services.ucf-fe.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true
