version: '3'
services:
  ucf-fe:
    image: docker.pkg.github.com/vijaystroup/ucf-fe/ucf-fe:latest
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.ucf_fe-http.rule=Host(`ucffe.example.com`)
        - traefik.http.routers.ucf_fe-http.entrypoints=http
        - traefik.http.routers.ucf_fe-http.middlewares=https-redirect
        - traefik.http.routers.ucf_fe-https.rule=Host(`ucffe.example.com`)
        - traefik.http.routers.ucf_fe-https.entrypoints=https
        - traefik.http.routers.ucf_fe-https.tls=true
        - traefik.http.routers.ucf_fe-https.tls.certresolver=le
        - traefik.http.services.ucf_fe.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true
