import Head from 'next/head'
import Nav from '../components/nav'
import Pdf from '../components/pdf'
import Code from '../components/code'
import style from '../styles/home.module.scss'
import Footer from '../components/footer'
import { useState } from 'react'

export default function Home() {
  const [theme, setTheme] = useState(0)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={style.all}>
        <header>
          <Nav />
        </header>
        <main className={style.main}>
          <section className={style.left}>
            <Pdf />
          </section>
          <div id={style.bar}></div>
          <section className={style.right}>
            <Code theme={theme ? 'light' : 'dark'} />
          </section>
        </main>
        <Footer setTheme={setTheme} />
      </div>
    </>
  )
}
